frontend:
  replicaCount: 1
  image:
    repository: ghcr.io/nguyenhoangle070105/multimodal-fake-news-frontend
    tag: 84dd263d1d5cc0cd39c61a13cfe184742e0177b0
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80

backend:
  replicaCount: 1
  image:
    repository: ghcr.io/nguyenhoangle070105/multimodal-fake-news-backend
    tag: 84dd263d1d5cc0cd39c61a13cfe184742e0177b0
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 5000
