frontend:
  replicaCount: 1
  image:
    repository: ghcr.io/nguyenhoangle070105/multimodal-fake-news-frontend
    tag: 3f7478a2b8e1cf248a98c361fb30241fdd92698a
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80

backend:
  replicaCount: 1
  image:
    repository: ghcr.io/nguyenhoangle070105/multimodal-fake-news-backend
    tag: 3f7478a2b8e1cf248a98c361fb30241fdd92698a
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 5000
