frontend:
  replicaCount: 1
  image:
    repository: ghcr.io/nguyenhoangle070105/multimodal-fake-news-frontend
    tag: 6538d2ea1cab70f4c9c2633080ec0d624aef5036
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80

backend:
  replicaCount: 1
  image:
    repository: ghcr.io/nguyenhoangle070105/multimodal-fake-news-backend
    tag: 6538d2ea1cab70f4c9c2633080ec0d624aef5036
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 5000
